In [1]:
import numpy as np

In [15]:
M = np.asarray([[512, -800, 0, 800],[512,0,-800,1600],[1,0,0,0]])
M.shape

(3, 4)

In [14]:
X = np.asarray([[4],[0],[0],[1]])
X.shape

(4, 1)

In [19]:
M@X

array([[2848],
       [3648],
       [   4]])

#### Q1

In [2]:
lst = []
E = [[321.747,309.140,30.086,880,214],[305.749,311.649,30.356,43,203],
     [307.694,312.356,30.416,270,197],[310.149,307.186,29.298,886,347],
    [311.937,310.105,29.216,745,302],[311.202,307.572,30.682,943,128],
    [307.106,306.878,28.660,476,590],[309.317,312.490,30.230,419,214],
    [307.435,310.151,29.318,317,335],[308.253,306.300,28.881,783,521],
    [306.650,309.301,28.905,235,427],[308.069,306.831,29.189,665,429],
    [309.671,308.834,29.029,665,362],[308.255,309.955,29.267,427,333],
    [307.546,308.613,28.963,412,415],[311.036,309.206,28.913,746,351],
    [307.519,308.175,29.069,434,415],[309.950,311.262,29.990,525,234],
    [312.160,310.772,29.080,716,308],[311.988,312.709,30.514,602,187]]


In [3]:
lst = []
# v = [305.749,311.649,30.356,43,203]

# s1+=f'{i for i in v[0:3]}' 
# s1+=f'{1,0,0,0,0}'
# s1+=f'{-v[3]*i for i in v[0:3]}'
# s1

# s2+=f'0,0,0,0,'
for v in E:
    s1 = []
    s2 = []
    s2+=[0]*4
    for i in v[0:3]:
        s1.append(i)
        s2.append(i)
    s2+=[1]

    s1+=[1]
    s1+=[0]*4
    for i in v[0:3]:
        s1.append(-i*v[3])
        s2.append(-i*v[4])
    s1.append(-v[3])
    s2.append(-v[4])
    # int(s1.split(','))
    s1,s2
    lst.append(s1)
    lst.append(s2)
# lst

In [4]:
# A = np.asarray([[321.747,309.140,30.086,1,0,0,0,0,-880*312.747,-880*30.086,-880],
#                [0,0,0,0,312.747,309.140,30.086,1,-214*312.747,-214*312.747,-214*309.140,-214*30.086,-214],
#                [305.796,311.649,30.356,1,0,0,0,0,-43*305.796,-43*311.649,-43*30.356,-43],
#                 [0,0,0,0,305.796,311.649,30.356,1,-203*305.796,-203*311.649,-43*30.356,-203],
#                [307.694,312.356,30.416,1,0,0,0,0,-270*307.694,-270*312.356,-270*30.416,-270],
#                [0,0,0,0,307.694,312.356,30.416,-197*307.694,-197*312.356,-197*30.416,-197]])

In [5]:
b=[]
for i in E:
    b.append(i[-2:])
b = list(np.concatenate(b).flat)
b = [[i] for i in b]
b = np.asarray(b)
b.shape

(40, 1)

In [6]:
# lst
# k = [1,1,1,1,1]
# k.append([11,22])
# k

In [7]:
A = np.asarray(lst)
A.shape

(40, 12)

In [8]:
M = []
M = np.linalg.lstsq(A,b)[0]
# M = np.append(M,1)
M
M = np.reshape(M,(3,4))
M

C:\Users\KHADGA~1\AppData\Local\Temp/ipykernel_13268/4232564574.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  M = np.linalg.lstsq(A,b)[0]


array([[ 4.98824634e-14, -1.19583163e-14,  2.01748951e-13,
        -1.72502877e-11],
       [ 7.81059245e-16,  2.21373484e-14, -3.77597123e-15,
        -6.85046469e-12],
       [ 3.64291930e-17,  6.70036943e-17,  2.38903949e-16,
        -1.00000000e+00]])

In [9]:
M = np.linalg.lstsq(A,b)
M = np.append(M,1)
M = np.reshape(M,(3,4))
M

C:\Users\KHADGA~1\AppData\Local\Temp/ipykernel_13268/4232833868.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  M = np.linalg.lstsq(A,b)
C:\Users\KHADGA JYOTH ALLI\anaconda3\lib\site-packages\numpy\lib\function_base.py:4811: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = asanyarray(arr)


ValueError: cannot reshape array of size 5 into shape (3,4)

In [10]:
b= [0]*len(b)
b

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [11]:
U,S,Vh = np.linalg.svd(A)
M = Vh[-1,:]
M = np.reshape(M,(3,4))
M

array([[ 2.04983984e-03,  1.21720953e-03, -2.20303232e-03,
        -9.39929354e-01],
       [ 4.87459881e-04,  8.02522553e-04, -1.86467461e-03,
        -3.41344347e-01],
       [ 2.03219058e-06,  2.75155559e-06, -2.49136573e-06,
        -1.39651144e-03]])

In [4]:
M = np.array([[ 2.04983984e-03,  1.21720953e-03, -2.20303232e-03,
        -9.39929354e-01],
       [ 4.87459881e-04,  8.02522553e-04, -1.86467461e-03,
        -3.41344347e-01],
       [ 2.03219058e-06,  2.75155559e-06, -2.49136573e-06,
        -1.39651144e-03]])
M.shape

(3, 4)

In [15]:
H = M[:,:3]
h = M[:,3].reshape(3,1)
H_inv = np.linalg.inv(H)
H_inv

array([[ 7.98291139e+02, -7.72255649e+02, -1.27904015e+05],
       [-6.56434973e+02, -1.60587068e+02,  7.00655896e+05],
       [-7.38300214e+01, -8.07282076e+02,  2.68113311e+05]])

In [16]:
R_T,K_inv = np.linalg.qr(H_inv)


In [26]:
R_T 

array([[-0.77043269, -0.4193071 , -0.48022394],
       [ 0.63352696, -0.4193599 , -0.65021601],
       [ 0.07125353, -0.80518248,  0.58873093]])

In [27]:
np.linalg.inv(R_T.T)

array([[-0.77043269, -0.4193071 , -0.48022394],
       [ 0.63352696, -0.4193599 , -0.65021601],
       [ 0.07125353, -0.80518248,  0.58873093]])

In [30]:
K_inv

array([[-1.03615949e+03,  4.35713059e+02,  5.61529854e+05],
       [ 0.00000000e+00,  1.04116544e+03, -4.56076066e+05],
       [ 0.00000000e+00,  0.00000000e+00, -2.36308514e+05]])